info:
    app:
       name: {build.app.name}
       group: {build.app.group}
       description: {build.app.description}
       version: {build.app.version}
       buildtime: {build.app.buildtime}

spring:
        application:
             name: {build.app.name}

server:
        port: ${HTTP_PORT:9080}
        tomcat:
             uri-encoding: ${URI_ENCODING:UTF-8}

watsonwork:
        webhook:
            secret: ${WEBHOOK_SECRET:o1m9c3za2i2pi40b20pyk18alg53bmk6}
        app:
            id: ${APP_ID:355d4a5f-eed8-443d-a315-cf95e7e63818}
            secret: ${APP_SECRET:3ROXQathKn00VOlVcfEmPCh8hW7B}
        api:
            uri: ${WATSON_WORK_API_URI:https://api.watsonwork.ibm.com}
            oauth: ${WATSON_WORK_OAUTH:/oauth/authorize}


jira:
    api:
        uri: ${JIRA_API_URI:https://watsonworkspace.atlassian.net}
        username: ${JIRA_API_USERNAME:bhumitp23+jira@gmail.com}
        password: ${JIRA_API_PASSWORD:qFf9T5fDyTJBN2YmTjULB664}