info:
    app:
       name: {build.app.name}
       group: {build.app.group}
       description: {build.app.description}
       version: {build.app.version}
       buildtime: {build.app.buildtime}

spring:
        application:
             name: {build.app.name}

server:
        port: ${HTTP_PORT:9080}
        tomcat:
             uri-encoding: ${URI_ENCODING:UTF-8}

watsonwork:
        webhook:
            secret: ${WEBHOOK_SECRET:6d42h9qqex8c80f7viqgajxqshy3j3qx}
        app:
            id: ${APP_ID:69577618-b697-4de8-b14a-7789633f9df6}
            secret: ${APP_SECRET:D4UhsN1Awy1_pk_CG3lMLV-sapPg}
        api:
            uri: ${WATSON_WORK_API_URI:https://api.watsonwork.ibm.com}
            oauth: ${WATSON_WORK_OAUTH:/oauth/authorize}


jira:
    api:
        uri: ${JIRA_API_URI:https://ibmworkspace.atlassian.net}
        username: ${JIRA_API_USERNAME:apenrose@ie.ibm.com}
        password: ${JIRA_API_PASSWORD:Shithead100@}