info:
    app:
       name: {build.app.name}
       group: {build.app.group}
       description: {build.app.description}
       version: {build.app.version}
       buildtime: {build.app.buildtime}

spring:
        application:
             name: {build.app.name}

server:
        port: ${HTTP_PORT:9080}
        tomcat:
             uri-encoding: ${URI_ENCODING:UTF-8}
management:
  security:
      enabled: false

watsonwork:
        webhook:
            secret: ${WEBHOOK_SECRET:k2oslj2jrr5g94q1q92ykxc7ev9y4hbj}
        app:
            id: ${APP_ID:2b8db1d2-f660-4eb2-9966-4e6a2b7415d2}
            secret: ${APP_SECRET:0rINTyc07cDyF8CayILjBt_bLiJN}
        api:
            uri: ${WATSON_WORK_API_URI:https://api.watsonwork.ibm.com}
            oauth: ${WATSON_WORK_OAUTH:/oauth/authorize}


jira:
    api:
        uri: ${JIRA_API_URI:https://ibmworkspace.atlassian.net}
        username: ${JIRA_API_USERNAME:apenrose@ie.ibm.com}
        password: ${JIRA_API_PASSWORD:Shithead100@}